name: InnerEye
channels:
  - defaults
  - pytorch
dependencies:
  - pip=20.1.1
  - python=3.7.3
  - pytorch=1.8.0
  - python-blosc==1.7.0
  - torchvision=0.9.0
  - pip:
      - -r file:requirements.txt
