# This is a initial selection of transformations that we think make sense for hystopathology images
augmentation:
  use_random_horizontal_flip: True
  use_random_affine: True
  use_random_color: True
  use_random_crop: False
  use_gamma_transform: True
  use_random_erasing: False
  add_gaussian_noise: True
  use_elastic_transform: False
  # TODO add vertical flip
  random_horizontal_flip:
    prob: 0.5
  random_affine:
    # TODO set fix angles (90, 180)
    max_angle: 180
    max_horizontal_shift: 0.00
    max_vertical_shift: 0.00
    max_shear: 0
  random_color:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.0
  gaussian_noise:
    std: 0.05