name: PyTorchTest
channels:
  - defaults
  - pytorch
dependencies:
  - pip=20.1.1
  - python=3.7.3
  - pytorch=1.8.0
  - pip:
      - azureml-sdk==1.28.0
      - flake8==3.8.3
      - numpy==1.19.1
      - pandas==1.1.0
      - pytest==6.0.1
      - pytest-cov==2.10.1
      - pytest-forked==1.3.0
      - pytest-xdist==1.34.0
