steps:
  - template: checkout.yml

  - template: store_settings.yml

  - bash: |
      sudo conda env update --file environment.yml --name InnerEye
      source activate InnerEye
      pip freeze
    failOnStderr: false
    displayName: Create full Conda environment and print package list

